export const initialState = {
  activeSignalId: "sig-002",
  activeThemeId: "theme-onboarding",
  lastUpdated: "2026-08-26T14:55:00+05:30",
  signals: [
    {
      id: "sig-001",
      source: "Community Forum",
      sourceType: "forum",
      author: "Maya R.",
      channel: "Launch Feedback",
      timestamp: "2026-08-24T16:40:00+05:30",
      title: "New users cannot find the migration checklist",
      excerpt:
        "The import worked, but I missed the setup checklist and only found it after searching docs for ten minutes.",
      url: "https://example.com/community/migration-checklist",
      confidence: "high",
      priority: "high",
      themes: ["theme-onboarding", "theme-docs"],
      evidenceTags: ["docs", "activation", "migration"],
      status: "unreviewed",
    },
    {
      id: "sig-002",
      source: "Support Inbox",
      sourceType: "support",
      author: "Support Triage",
      channel: "Tier 1",
      timestamp: "2026-08-25T09:25:00+05:30",
      title: "Spike in workspace import tickets",
      excerpt:
        "Seven tickets in 24 hours mention import success followed by confusion about the next required admin step.",
      url: "https://example.com/support/import-ticket-cluster",
      confidence: "high",
      priority: "critical",
      themes: ["theme-onboarding"],
      evidenceTags: ["tickets", "activation", "admin"],
      status: "selected",
    },
    {
      id: "sig-003",
      source: "Public Changelog Comment",
      sourceType: "web",
      author: "Eli K.",
      channel: "Release Notes",
      timestamp: "2026-08-25T13:10:00+05:30",
      title: "Release notes hide the admin follow-up",
      excerpt:
        "The release note explains import formats well, but the admin handoff is buried below the API examples.",
      url: "https://example.com/changelog/import-release",
      confidence: "medium",
      priority: "medium",
      themes: ["theme-docs"],
      evidenceTags: ["release-notes", "admin", "docs"],
      status: "unreviewed",
    },
    {
      id: "sig-004",
      source: "Customer Advisory Board",
      sourceType: "meeting",
      author: "CAB Notes",
      channel: "August Review",
      timestamp: "2026-08-23T18:05:00+05:30",
      title: "Admins want a completion receipt",
      excerpt:
        "Two admins asked for a clear receipt that says what was imported, what failed, and what they should do next.",
      url: "https://example.com/notes/admin-receipt",
      confidence: "high",
      priority: "high",
      themes: ["theme-onboarding", "theme-trust"],
      evidenceTags: ["admin", "receipt", "trust"],
      status: "selected",
    },
    {
      id: "sig-005",
      source: "Competitor Watch",
      sourceType: "market",
      author: "Analyst Desk",
      channel: "Ecosystem Scan",
      timestamp: "2026-08-25T20:30:00+05:30",
      title: "Competitor ships guided import receipt",
      excerpt:
        "A competitor now shows a guided post-import checklist with owners, dates, and one-click escalation.",
      url: "https://example.com/market/guided-import-receipt",
      confidence: "medium",
      priority: "medium",
      themes: ["theme-trust"],
      evidenceTags: ["competitor", "checklist", "admin"],
      status: "unreviewed",
    },
    {
      id: "sig-006",
      source: "Sales Call",
      sourceType: "meeting",
      author: "AE Summary",
      channel: "Enterprise Pipeline",
      timestamp: "2026-08-22T11:15:00+05:30",
      title: "Buyer asks who owns post-import setup",
      excerpt:
        "The champion liked the importer, then asked whether IT, RevOps, or the vendor owns the final validation step.",
      url: "https://example.com/sales/post-import-ownership",
      confidence: "medium",
      priority: "medium",
      themes: ["theme-onboarding", "theme-trust"],
      evidenceTags: ["sales", "ownership", "validation"],
      status: "unreviewed",
    },
  ],
  themes: [
    {
      id: "theme-onboarding",
      name: "Post-import onboarding gap",
      summary:
        "Users complete the import but do not know the required next step, owner, or validation path.",
      signalIds: ["sig-001", "sig-002", "sig-004", "sig-006"],
      confidence: "high",
      reviewState: "needs_edit",
    },
    {
      id: "theme-docs",
      name: "Docs and release notes bury next steps",
      summary:
        "The guidance exists, but it is split across docs and release notes instead of appearing in the workflow.",
      signalIds: ["sig-001", "sig-003"],
      confidence: "medium",
      reviewState: "proposed",
    },
    {
      id: "theme-trust",
      name: "Admins need proof and ownership",
      summary:
        "Admins want a receipt that clarifies import outcomes, unresolved items, and accountable owners.",
      signalIds: ["sig-004", "sig-005", "sig-006"],
      confidence: "medium",
      reviewState: "proposed",
    },
  ],
  brief: {
    title: "Customer Impact Brief: Admin Import Activation",
    status: "draft",
    updatedBy: "Seed scenario",
    sections: [
      {
        id: "claim-001",
        label: "Primary risk",
        claim:
          "The import launch is creating an activation gap after technical success, especially for admin-owned workspaces.",
        evidenceSignalIds: ["sig-002", "sig-004", "sig-006"],
        reviewState: "needs_edit",
      },
      {
        id: "claim-002",
        label: "Evidence pattern",
        claim:
          "The strongest signals cluster around missing next-step ownership, not import failures.",
        evidenceSignalIds: ["sig-001", "sig-002", "sig-004"],
        reviewState: "proposed",
      },
      {
        id: "claim-003",
        label: "Opportunity",
        claim:
          "A post-import receipt with owners and validation steps would directly address support, customer, and market signals.",
        evidenceSignalIds: ["sig-004", "sig-005"],
        reviewState: "proposed",
      },
    ],
  },
  actions: [
    {
      id: "act-001",
      title: "Add post-import receipt to the product flow",
      owner: "Product",
      due: "2026-08-30",
      rationale:
        "The receipt addresses the highest-confidence support and advisory board signals.",
      evidenceSignalIds: ["sig-002", "sig-004"],
      state: "proposed",
    },
    {
      id: "act-002",
      title: "Move migration checklist above API examples",
      owner: "Docs",
      due: "2026-08-28",
      rationale:
        "Docs feedback suggests next steps are present but not findable at the moment of need.",
      evidenceSignalIds: ["sig-001", "sig-003"],
      state: "needs_edit",
    },
    {
      id: "act-003",
      title: "Prepare admin handoff email template",
      owner: "Lifecycle",
      due: "2026-09-02",
      rationale:
        "Sales and CAB evidence both point to ownership confusion after import completion.",
      evidenceSignalIds: ["sig-004", "sig-006"],
      state: "approved",
    },
  ],
  auditTrail: [
    {
      id: "audit-001",
      actor: "Agent",
      action: "Grouped 6 requests into 3 patterns",
      timestamp: "2026-08-26T14:49:00+05:30",
      detail: "Grouped customer requests by activation, documentation, and trust patterns.",
    },
    {
      id: "audit-002",
      actor: "Agent",
      action: "Drafted 3 brief claims with evidence",
      timestamp: "2026-08-26T14:51:00+05:30",
      detail: "Each claim includes at least two supporting customer requests.",
    },
    {
      id: "audit-003",
      actor: "Human",
      action: "Approved lifecycle handoff action",
      timestamp: "2026-08-26T14:54:00+05:30",
      detail: "Kept product and docs actions in review.",
    },
  ],
};
